name = "PMO"
uuid = "fbf10557-b722-42fa-b9dc-91a07c0260e4"
authors = ["mourrain <bernard.mourrain@inria.fr>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
